APP_STL := gnustl_static

APP_CPPFLAGS := -frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char
APP_LDFLAGS := -latomic


ifeq ($(NDK_DEBUG),1)
  APP_CPPFLAGS += -DCOCOS2D_DEBUG=1
  APP_OPTIM := debug
else
  APP_CPPFLAGS += -DNDEBUG
  APP_OPTIM := release
endif

CC_USE_CURL := 0
CC_USE_CCSTUDIO := 1
CC_USE_CCBUILDER := 0
CC_USE_SPINE := 0
CC_USE_PHYSICS := 0
CC_USE_TIFF := 0
CC_USE_WEBP := 0
CC_USE_JPEG := 0
CC_USE_3D := 0
CC_USE_SQLITE := 0
CC_USE_RUNTIME := 0